import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from schema_validation import validate_report

SEVERITY_SCORES = {
    "critical": 10,
    "high": 7,
    "medium": 5,
    "low": 2,
    "info": 1
}


def classify_entity(entity):
    entity_type = entity.get("type", "")

    if entity_type in ["ip", "domain"]:
        return "infrastructure"

    if entity_type in ["email", "username", "social_profile"]:
        return "identity"

    if entity_type in ["organization", "address", "phone"]:
        return "organization"

    if entity_type in ["technology", "certificate"]:
        return "technology"

    return "other"


def build_summary(scan):
    entities = scan.get("entities", [])
    events = scan.get("events", [])

    entity_counter = Counter()

    for entity in entities:
        entity_counter[entity["type"]] += 1

    return {
        "target": scan.get("target"),
        "scan_date": scan.get("scan_date"),
        "total_entities": len(entities),
        "total_events": len(events),
        "entity_breakdown": dict(entity_counter)
    }


def build_findings(scan):
    findings = []

    entities = scan.get("entities", [])

    grouped = {}

    for entity in entities:
        category = classify_entity(entity)

        grouped.setdefault(category, [])
        grouped[category].append(entity)

    for category, values in grouped.items():
        findings.append({
            "title": f"{category.title()} Assets Discovered",
            "severity": "info",
            "count": len(values),
            "category": category,
            "items": values
        })

    return findings


def calculate_risk(findings):
    score = 0

    for finding in findings:
        severity = finding.get("severity", "info")
        score += SEVERITY_SCORES.get(severity, 1)

    if score >= 50:
        rating = "critical"
    elif score >= 30:
        rating = "high"
    elif score >= 15:
        rating = "medium"
    else:
        rating = "low"

    return {
        "score": score,
        "rating": rating
    }


def build_report(scan):
    summary = build_summary(scan)
    findings = build_findings(scan)
    risk = calculate_risk(findings)

    report = {
        "report_metadata": {
            "generated_at": datetime.now(
                timezone.utc
            ).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "generator": "OSIRIS",
            "version": "1.0"
        },
        "summary": summary,
        "risk_assessment": risk,
        "findings": findings,
        "events": scan.get("events", []),
        "raw_statistics": {
            "entity_count": len(scan.get("entities", [])),
            "event_count": len(scan.get("events", []))
        }
    }

    validate_report(report)

    return report


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "scan_file",
        help="raw_scan.json generated by sense_clean.py"
    )

    parser.add_argument(
        "output_file",
        help="report output path"
    )

    args = parser.parse_args()

    scan = load_json(args.scan_file)

    report = build_report(scan)

    save_json(report, args.output_file)

    print(
        f"Report written to {args.output_file}"
    )